[versions]
kotlin = "1.8.20"

# MineSec
mineSecMineHades = "1.10.105.12.69"
mineSecMsaLibs = "2.0.133"
minesecToolKit = "1.1.13"
visaSensory = "2.2"

# Android
androidGradlePlugin = "8.1.1"
androidxAppCompat = "1.6.1"
androidxCore = "1.12.0"
androidxLifecycle = "2.6.2"
androidxConstraintLayout = "2.1.4"
androidxSwipeLayout = "1.1.0"
androidxPreference = "1.2.1"

# UI
material = "1.9.0"
flexbox = "3.0.0"
coil = "2.4.0"
zxing = "4.3.0"
signaturePad = "1.3.1"
lottie = "6.1.0"

# Multithreading
coroutines = "1.7.3"
rxjava2 = "2.2.21"
rxjava2Android = "2.1.1"

# Network
okhttp = "4.9.3" # https://github.com/square/okhttp/blob/master/CHANGELOG.md
retrofit = "2.9.0" # https://github.com/square/retrofit/blob/master/CHANGELOG.md

# Serialization
gson = "2.9.0"
serializationJson = "1.5.1"

# Security
tink = "1.7.0"
androidxSecurityCrypto = "1.1.0-alpha06"
androidxSecurityIdCredential = "1.0.0-alpha03"

# Test
junit4 = "4.13.2"
androidxTestExt = "1.1.5"
androidxEspresso = "3.5.1"

# Debug
leakcanary = "2.11"

# Annotations, compiler plugin
androidAnnotation = "1.7.0"
lombok = "1.18.24"
ksp = "1.9.0-1.0.11"

# Services
firebaseBom = "30.3.1" # https://firebase.google.com/support/release-notes/android
firebaseCrashlyticsPlugin = "2.9.2"
gmsPlugin = "4.3.14"
#gmsSafetynet = "18.0.1"
playIntegrity = "1.1.0"

# Sentry log
sentryAndroid = "7.3.0"

# Language
lingver = "1.3.0"

# MPOS
easyLinkSdk = "2.09.06"
ecrProtocol = "1.01.00"
glCommon = "1.07.00"
glUtils = "1.00.00"

# PayServer
payServer = "1.0.1"
posLib = "1.2.4"

# printer
ominidriver = "0.0.1"
nexgodriver = "3.08.002"


# ULID
ulidver = "5.2.3"
runner = "1.0.2"
espressoCore = "3.0.2"
appcompatV7 = "28.0.0"

[libraries]
# MineSec
ms-sdk-minehades = { module = "com.theminesec.sdk:minehades", version.ref = "mineSecMineHades" }
ms-sdk-minehades-stage = { module = "com.theminesec.sdk:minehades-stage", version.ref = "mineSecMineHades" }
ms-app-msa-lib-model = { module = "com.theminesec.app:lib-model", version.ref = "mineSecMsaLibs" }
ms-app-msa-lib-ui = { module = "com.theminesec.app:lib-ui", version.ref = "mineSecMsaLibs" }
minesec-toolkit = { module = "io.github.songyao1987:MinesecToolKit", version.ref = "minesecToolKit" }
visa-sensory = { module = "com.theminesec.utils:visa-sensory-branding", version.ref = "visaSensory" }

# Androidx
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidxSwipeLayout" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidxPreference" }

# UI
material = { module = "com.google.android.material:material", version.ref = "material" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
zxing-androidembedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxing" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
signaturepad = { module = "com.github.gcacace:signature-pad", version.ref = "signaturePad" }

# Multithreading
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
rxjava2 = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava2" }
rxjava2-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxjava2Android" }

# Network
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofit" }
retrofit-gsonconverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# Serialization
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

# Security
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "androidxSecurityCrypto" }
androidx-security-identityCredential = { group = "androidx.security", name = "security-identity-credential", version.ref = "androidxSecurityIdCredential" }

# Test
junit4 = { module = "junit:junit", version.ref = "junit4" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }

# Debug
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

# Annotations processing
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidAnnotation" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# Service
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
#gms-safetynet = { group = "com.google.android.gms", name = "play-services-safetynet", version.ref = "gmsSafetynet" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "playIntegrity" }

# Sentry log
sentry-android = { module = "io.sentry:sentry-android", version.ref = "sentryAndroid" }

# Language
lingver = { module = "com.github.YarikSOffice:lingver", version.ref = "lingver" }

# MPOS
mpos-easylink-sdk = { module = "com.theminesec.mpos:easy-link-sdk", version.ref = "easyLinkSdk" }
mpos-ecr-protocol = { module = "com.theminesec.mpos:ecr-protocol", version.ref = "ecrProtocol" }
mpos-gl-common = { module = "com.theminesec.mpos:gl-common", version.ref = "glCommon" }
mpos-gl-utils = { module = "com.theminesec.mpos:gl-utils", version.ref = "glUtils" }

# PayServer
payServer = { module = "com.theminesec.app:payserver", version.ref = "payServer" }
poslib = { module = "com.theminesec.app:poslib", version.ref = "posLib" }

# printer
ominidriver = { module = "com.theminesec.printer:ominidriver", version.ref = "ominidriver" }
nexgodriver = { module = "com.theminesec.printer:nexgo", version.ref = "nexgodriver" }

# ULID
ulid = { module = "com.github.f4b6a3:ulid-creator", version.ref = "ulidver" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }
espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompatV7" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }

firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
gms-googleServices = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
